spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_container_db
    username: root
    password: admin
  sql:
    init:
      mode: never
  flyway:
    url: jdbc:mysql://localhost:3306/test_container_db
    locations: classpath:db/migration
    user: root
    password: admin
#    baselineOnMigrate: true


